name: Run Automated Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get install -y chromium-chromedriver
          
      - name: Run tests
        run: |
          pytest web-tests/tests/ --browser=chrome --alluredir=./allure-results
          
      - name: Upload Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: ./allure-results
